### ISSUE TITLE
batch_size的大小问题

### ISSUE THREAD

**Issue by wenhaozheng-nju** [fingertap/test_parallel#1]
在dataparallel里，batch_size应该是平均分到n张卡的，假设n=5，batch_size=50，每张卡的计算量应该是10
而在分布式里，batch_size是指单个机器的计算量，如果此时batch_size=50，一个worker是一张卡，那么单卡的计算量应该是50

**Comment by fingertap** [comment]
这是之前修改后遗留的不公平的现象，已经修改，结果仍然是DP最慢，甚至8卡不如单卡。DDP加速效果很好。
